name: Build Minecraft Launcher APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      run: |
        # Создаем директорию для Android SDK
        mkdir -p $ANDROID_HOME

        # Скачиваем Command Line Tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm commandlinetools-linux-9477386_latest.zip

        # ЯВНО добавляем в PATH
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        
        # Ждем обновления PATH
        sleep 2

    - name: Install Android packages
      run: |
        # Проверяем доступность sdkmanager
        which sdkmanager || echo "sdkmanager not found"
        
        # Принимаем лицензии
        yes | sdkmanager --licenses

        # Устанавливаем необходимые компоненты
        sdkmanager "platforms;android-33"
        sdkmanager "build-tools;33.0.0"
        sdkmanager "platform-tools"
        sdkmanager "cmdline-tools;latest"

    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "ndk.dir=$ANDROID_HOME/ndk/25.2.9519653" >> local.properties

    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: minecraft-launcher
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 7

    - name: Verify build
      run: |
        echo "=== Проверка сборки ==="
        ls -la app/build/outputs/apk/debug/
        echo "=== Размер APK ==="
        du -h app/build/outputs/apk/debug/*.apk