name: Code Quality Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      run: |
        # Создаем директорию для Android SDK
        mkdir -p $ANDROID_HOME

        # Скачиваем Command Line Tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm commandlinetools-linux-9477386_latest.zip

        # Добавляем в PATH
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

        # Принимаем лицензии
        yes | sdkmanager --licenses

        # Устанавливаем необходимые компоненты
        sdkmanager "platforms;android-33"
        sdkmanager "build-tools;33.0.0"
        sdkmanager "platform-tools"
        sdkmanager "cmdline-tools;latest"

    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties

    - name: Check Dependencies
      run: |
        chmod +x gradlew
        ./gradlew dependencies --no-daemon

    - name: Check Build Variants
      run: |
        ./gradlew tasks --group="build" --no-daemon

    - name: Validate Gradle Files
      run: |
        ./gradlew validateProjectStructure --no-daemon

    - name: Check for Vulnerabilities
      run: |
        ./gradlew dependencyInsight --dependency="*:*:*" --no-daemon

    - name: Generate Build Report
      run: |
        ./gradlew buildEnvironment --no-daemon

    - name: Upload Quality Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: quality-report
        path: |
          app/build/reports/
          build/reports/
        retention-days: 7